# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v2_5JciJwn0c4IW_dyFd8xYRFh3GeSKr
"""

! [ -e /content ] && pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

from fastbook import *

# Import library
from fastai.vision.all import *

# Dowload and extract standard dataset
path = untar_data(URLs.PETS)/'images'

# If first charcater is uppercase letter
def is_cat(x): return x[0].isupper()

'''
- path: The root path where the dataset is located.
- get_image_files(path): A function to retrieve image files from the specified path. The get_image_files function is likely provided by the fastai.vision.data module and returns a list of image file paths.
- valid_pct=0.2: Specifies that 20% of the data will be used for validation.
- seed=42: Sets the random seed for reproducibility.
- label_func=is_cat: Specifies the function used to determine the label for each image. In this case, it's the is_cat function that checks if the first character of the filename is uppercase.
- item_tfms=Resize(224): Applies a transformation to resize each image to a size of 224x224 pixels.
'''

dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224))

learn = vision_learner(dls, resnet34, metrics=error_rate)
learn.fine_tune(1)

uploader = widgets.FileUpload()
uploader

img = PILImage.create(uploader.data[0])
is_cat,_,probs = learn.predict(img)
print(f"Is this a cat?: {is_cat}.")
print(f"Probability it's a cat: {probs[1].item():.6f}")